name: CI
on:
  push:
jobs:
  e2e:
    name: E2E
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Clean Install
        run: npm ci && npm run postinstall
      - name: Test
        run: npm run postinstall && npm run test
      - name: Build App
        run: npm run build
      - name: Release
        run: npx --no-install semantic-release
